language: node_js

addons:
  ssh_known_hosts:
  - beta.fuelrats.com
  - cheddar.fuelrats.com

cache: yarn

before_script:
- scripts/choose-ga-id.sh

script:
- yarn run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_257dda796125_key -iv $encrypted_257dda796125_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

notifications:
  irc:
    on_success: always
    on_failure: always
    channels:
    - irc.us.fuelrats.com#rattech
    nick: TravisCI
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{result}'
    - 'Change view : %{compare_url}  Build details : %{build_url}'

deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis-deployment@cheddar.fuelrats.com:/var/www/beta.fuelrats.com/
  on:
    branch: develop

- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis-deployment@cheddar.fuelrats.com:/var/www/fuelrats.com/
  on:
    branch: master
